[tools]
node = "lts"
go = "latest"
ruby = "latest"
rust = "latest"

# CLI tools
eza = "latest"
bat = "latest"
fd = "latest"
ripgrep = "latest"
fzf = "latest"
jq = "latest"
zoxide = "latest"
sd = "latest"
jnv = "latest"
btop = { version = "latest", os = ["linux"] }
dust = "latest"
duf = "latest"
"aqua:dalance/procs" = "latest"
delta = "latest"
xh = "latest"
doggo = "latest"
"aqua:fujiapple852/trippy" = "latest"
tlrc = "latest"
hyperfine = "latest"
"cargo:navi" = "latest"
atuin = "latest"
lazygit = "latest"
gh = "latest"
yazi = "latest"
starship = "latest"
ghq = "latest"
"aqua:neovim/neovim" = "latest"
zellij = "latest"
tmux = "latest"
"gem:tmuxinator" = "latest"
"cargo:tree-sitter-cli" = "latest"

[settings]
auto_install = true

[settings.ruby]
compile = false
