[tools]
node = "lts"
go = "latest"
rust = "latest"

# CLI tools
eza = "latest"
bat = "latest"
fd = "latest"
ripgrep = "latest"
fzf = "latest"
jq = "latest"
zoxide = "latest"
sd = "latest"
jnv = "latest"
btop = { version = "latest", os = ["linux"] }
"cargo:du-dust" = "latest"
duf = "latest"
"github:dalance/procs" = "latest"
delta = "latest"
xh = "latest"
doggo = "latest"
"aqua:fujiapple852/trippy" = "latest"
"github:tldr-pages/tlrc" = "latest"
"github:sharkdp/hyperfine" = "latest"
"cargo:navi" = "latest"
atuin = "latest"
lazygit = "latest"
jj = "latest"
gh = "latest"
yazi = "latest"
starship = "latest"
ghq = "latest"
"aqua:neovim/neovim" = "latest"
zellij = "latest"
tmux = "latest"
"github:tree-sitter/tree-sitter" = "latest"
"cargo:psmux" = { version = "latest", os = ["windows"] }
"cargo:worktrunk" = { version = "latest", os = ["linux", "darwin"] }
claude-squad = "latest"
"github:asheshgoplani/agent-deck" = { version = "latest", os = ["linux", "darwin"] }
bun = "latest"
pnpm = "latest"
codex = "latest"
"github:abhinav/git-spice" = "latest"
rtk = "latest"
"aqua:noborus/ov" = "latest"
"aqua:walles/moor" = "latest"
python = "latest"
ffmpeg = "latest"
sheldon = "latest"
turso = "latest"
glow = "latest"
circleci = "latest"
"npm:@playwright/cli" = "latest"

[settings]
auto_install = true
not_found_auto_install = false

[settings.ruby]
compile = true

[settings.python]
github_attestations = false
